package com.tbce.calc.reader

// Generated by tools/build_packs.py. Do not edit.
internal object K {
    private val a = byteArrayOf(-104, -84, -123, 10, 107, 110, -93, 60, -52, 37, -30, -7, 30, -33, 100, 7, 32, 40, 122, 68, 58, 82, 126, -88, 4, -122, 92, -70, -76, -104, 121, 55)
    private val b = byteArrayOf(-40, -1, 80, -20, -113, 40, 92, 123, -56, 108, -60, 35, 42, -45, 49, -36, 3, -66, -59, -45, -58, -127, -31, -57, -80, 69, 121, -12, 126, -77, 66, -122)
    fun get(): ByteArray = ByteArray(32) { (a[it].toInt() xor b[it].toInt()).toByte() }
}
